// Build a Markdown reference document from an inspected MCP server.
// Output is plain CommonMark — no GFM extensions required, so it pastes
// cleanly into GitHub READMEs, Notion, Slack, anywhere.

import { renderSignature } from "./schema-render.js";

export function buildMarkdown(state) {
  const lines = [];
  const name = state.serverInfo?.name || "MCP Server";
  const version = state.serverInfo?.version ? ` \`v${state.serverInfo.version}\`` : "";
  lines.push(`# ${name}${version}`);
  lines.push("");
  lines.push(`- **URL**: \`${state.url}\``);
  lines.push(`- **Protocol**: \`${state.protocolVersion}\``);
  lines.push(`- **Inspected**: ${state.inspectedAt}`);
  lines.push("");

  if (state.instructions) {
    lines.push("## Server instructions");
    lines.push("");
    lines.push(quote(state.instructions));
    lines.push("");
  }

  emitTools(lines, state.tools);
  emitResources(lines, state.resources);
  emitTemplates(lines, state.resourceTemplates);
  emitPrompts(lines, state.prompts);

  lines.push("---");
  lines.push("Generated by [MCP Unpack](https://vinovator.github.io/my-ai-tools/mcp-unpack/).");
  return lines.join("\n");
}

function emitTools(lines, tools) {
  if (!tools || !tools.length) return;
  lines.push(`## Tools (${tools.length})`);
  lines.push("");
  for (const t of tools) {
    lines.push(`### \`${t.name}\``);
    lines.push("");
    if (t.description) {
      lines.push(t.description);
      lines.push("");
    }
    const annotations = listAnnotations(t);
    if (annotations.length) {
      lines.push(`_Annotations:_ ${annotations.join(", ")}`);
      lines.push("");
    }
    lines.push("```");
    lines.push(renderSignature(t.name, t.inputSchema));
    lines.push("```");
    lines.push("");
    if (t.inputSchema && Object.keys(t.inputSchema).length) {
      lines.push("<details><summary>Input schema</summary>");
      lines.push("");
      lines.push("```json");
      lines.push(JSON.stringify(t.inputSchema, null, 2));
      lines.push("```");
      lines.push("");
      lines.push("</details>");
      lines.push("");
    }
  }
}

function listAnnotations(tool) {
  const a = tool.annotations || tool;
  const out = [];
  if (a.readOnlyHint)    out.push("read-only");
  if (a.destructiveHint) out.push("destructive");
  if (a.idempotentHint)  out.push("idempotent");
  if (a.openWorldHint)   out.push("open-world");
  return out;
}

function emitResources(lines, resources) {
  if (!resources || !resources.length) return;
  lines.push(`## Resources (${resources.length})`);
  lines.push("");
  for (const r of resources) {
    lines.push(`### ${r.name || r.uri}`);
    lines.push("");
    lines.push(`- **URI**: \`${r.uri}\``);
    if (r.mimeType) lines.push(`- **MIME**: \`${r.mimeType}\``);
    if (r.description) {
      lines.push("");
      lines.push(r.description);
    }
    lines.push("");
  }
}

function emitTemplates(lines, templates) {
  if (!templates || !templates.length) return;
  lines.push(`## Resource Templates (${templates.length})`);
  lines.push("");
  for (const t of templates) {
    lines.push(`### ${t.name || t.uriTemplate}`);
    lines.push("");
    lines.push(`- **Template**: \`${t.uriTemplate}\``);
    if (t.mimeType) lines.push(`- **MIME**: \`${t.mimeType}\``);
    if (t.description) {
      lines.push("");
      lines.push(t.description);
    }
    lines.push("");
  }
}

function emitPrompts(lines, prompts) {
  if (!prompts || !prompts.length) return;
  lines.push(`## Prompts (${prompts.length})`);
  lines.push("");
  for (const p of prompts) {
    lines.push(`### \`${p.name}\``);
    lines.push("");
    if (p.description) {
      lines.push(p.description);
      lines.push("");
    }
    if (Array.isArray(p.arguments) && p.arguments.length) {
      lines.push("| Argument | Required | Description |");
      lines.push("| --- | :---: | --- |");
      for (const a of p.arguments) {
        const desc = (a.description || "").replace(/\|/g, "\\|").replace(/\n/g, " ");
        lines.push(`| \`${a.name}\` | ${a.required ? "yes" : "no"} | ${desc} |`);
      }
      lines.push("");
    }
  }
}

function quote(text) {
  return text.split("\n").map(l => `> ${l}`).join("\n");
}
